import Link from "next/link";
import { chQueryParams } from "@/lib/ch";
import { Icon } from "@/components/icon";
import { HelpTip } from "@/components/ui/help-tip";

export const dynamic = "force-dynamic";

interface EventRow {
  id: string;
  trace_id: string;
  name: string;
  kind: string;
  status: string;
  error_message: string | null;
  attributes: string;
  latency_ms: number | null;
  tokens_in: number | null;
  tokens_out: number | null;
  transcript_ref: string | null;
  pii_redactions: Array<{ field: string; type: string; action: string; count: number }>;
  zero_pii_mode: boolean;
  timestamp: string;
}

const KIND_LABEL: Record<string, string> = {
  agent: "agent",
  llm: "AI reply",
  tool: "tool call",
  retrieval: "lookup",
  checkpoint: "checkpoint",
  session: "session",
};

const KIND_TIP: Record<string, string> = {
  agent: "The agent itself starting or finishing work.",
  llm: "A reply generated by the language model.",
  tool: "Your agent calling an external tool or API.",
  retrieval: "Looking something up (docs, database, search).",
  checkpoint: "A marked decision point you instrumented with dx.checkpoint().",
  session: "The conversation session opening or closing.",
};

export default async function TraceDetailPage({
  params,
}: {
  params: Promise<{ conversationId: string }>;
}) {
  const { conversationId } = await params;
  const id = decodeURIComponent(conversationId);

  const events = await chQueryParams<EventRow>(
    "SELECT * FROM events WHERE conversation_id = {cid:String} ORDER BY timestamp ASC",
    { cid: id }
  );

  const minT = events.length > 0 ? new Date(events[0]!.timestamp).getTime() : 0;
  const maxT = events.length > 0 ? new Date(events[events.length - 1]!.timestamp).getTime() : 1;
  const span = Math.max(maxT - minT, 1);
  const failed = events.filter((e) => e.status === "error").length;

  return (
    <div className="px-6 pt-5">
      <Link href="/traces" className="text-[12px] text-gray-500 hover:text-gray-800">
        ← Conversations
      </Link>
      <div className="mt-1 flex items-baseline gap-3">
        <h1 className="font-mono text-[15px] font-semibold text-gray-900" title={id}>…{id.slice(-16)}</h1>
        <span className="text-[12px] text-gray-400">
          {events.length} steps · {failed} failed
        </span>
      </div>

      {failed > 0 && events.some((e) => e.error_message) && (
        <div className="mt-3 max-w-3xl rounded-lg border border-red-200 bg-red-50 p-3">
          <div className="text-[12px] font-semibold text-red-700">What happened</div>
          <ul className="mt-1 list-disc space-y-0.5 pl-4 text-[12px] leading-5 text-red-900">
            {events
              .filter((e) => e.error_message)
              .slice(0, 3)
              .map((e) => (
                <li key={e.id}>
                  <span className="font-medium">{e.name}:</span> {e.error_message}
                </li>
              ))}
          </ul>
          <p className="mt-1.5 text-[11px] text-red-700/80">
            Fix the step above (or add an instruction for its intent) and this conversation type recovers.
          </p>
        </div>
      )}

      <table className="mt-4 w-full border-separate border-spacing-0 text-[13px]">
        <thead>
          <tr className="text-left text-[12px] text-gray-500">
            <th className="w-8 border-b border-gray-200 py-2" title="Position in time"></th>
            <th className="border-b border-gray-200 py-2 pr-4 font-normal">Step</th>
            <th className="border-b border-gray-200 py-2 pr-4 font-normal">Type</th>
            <th className="border-b border-gray-200 py-2 pr-4 font-normal">Outcome</th>
            <th className="border-b border-gray-200 py-2 pr-4 text-right font-normal">
              Time
              <HelpTip text="How long this step took, plus AI tokens used (in → out)." />
            </th>
            <th className="border-b border-gray-200 py-2 font-normal">
              Privacy
              <HelpTip text="Sensitive data hidden before storage. Violet = something was redacted." />
            </th>
          </tr>
        </thead>
        <tbody>
          {events.map((e, idx) => {
            const t = new Date(e.timestamp).getTime();
            const offsetPct = Math.min(((t - minT) / span) * 100, 97);
            let attrsPreview = "";
            try {
              attrsPreview = JSON.stringify(JSON.parse(e.attributes), null, 1);
            } catch {
              attrsPreview = e.attributes;
            }
            const piiCount = (e.pii_redactions ?? []).reduce((a, r) => a + Number(r.count), 0);
            return (
              <tr key={e.id} className="align-top hover:bg-gray-50">
                <td className="border-b border-gray-100 py-2.5">
                  <span
                    className="ml-1 inline-block h-1.5 w-1.5 rounded-full bg-accent"
                    style={{ marginLeft: `${offsetPct}%` }}
                    title={`t+${t - minT}ms`}
                  />
                </td>
                <td className="border-b border-gray-100 py-2.5 pr-4">
                  <span className="font-medium text-gray-900">{e.name}</span>
                  {e.error_message && (
                    <span className="mt-0.5 block max-w-md whitespace-normal break-words font-mono text-[11px] leading-4 text-red-600">
                      {e.error_message}
                    </span>
                  )}
                  {attrsPreview !== "{}" && (
                    <details className="mt-0.5">
                      <summary className="cursor-pointer text-[11px] text-gray-400 hover:text-gray-600">
                        Show step details
                      </summary>
                      <pre className="mt-1 max-h-48 max-w-xl overflow-auto rounded-md border border-gray-200 bg-gray-50 p-2 font-mono text-[11px] leading-4 text-gray-600">
                        {attrsPreview}
                      </pre>
                    </details>
                  )}
                </td>
                <td className="border-b border-gray-100 py-2.5 pr-4 text-gray-600">
                  <span title={KIND_TIP[e.kind] ?? e.kind}>{KIND_LABEL[e.kind] ?? e.kind}</span>
                  {idx === 0 && (
                    <span className="ml-1.5 text-[10px] uppercase tracking-wide text-gray-400" title="First step of the conversation">start</span>
                  )}
                </td>
                <td className="border-b border-gray-100 py-2.5 pr-4">
                  <span
                    className={`rounded px-1.5 py-0.5 text-[11px] font-medium ${
                      e.status === "error" ? "bg-red-50 text-red-600" : "bg-emerald-50 text-emerald-600"
                    }`}
                    title={e.status === "error" ? "This step failed — see the message above." : "This step completed fine."}
                  >
                    {e.status === "error" ? "Failed" : "Passed"}
                  </span>
                </td>
                <td className="border-b border-gray-100 py-2.5 pr-4 text-right tabular-nums text-gray-600">
                  {e.latency_ms != null ? `${Math.round(Number(e.latency_ms))} ms` : "—"}
                  {(e.tokens_in != null || e.tokens_out != null) && (
                    <span className="block text-[11px] text-gray-400" title="AI tokens consumed (in) and produced (out) — drives cost.">
                      {Number(e.tokens_in ?? 0)} in · {Number(e.tokens_out ?? 0)} out
                    </span>
                  )}
                </td>
                <td className="border-b border-gray-100 py-2.5">
                  {piiCount > 0 ? (
                    <span className="inline-flex items-center gap-1 rounded bg-violet-50 px-1.5 py-0.5 text-[11px] font-medium text-accent" title="Sensitive values in this step were hidden before storage.">
                      <Icon name="shield" className="h-3 w-3" />
                      {piiCount} hidden
                    </span>
                  ) : (
                    <span className="text-gray-300">—</span>
                  )}
                  {e.zero_pii_mode && (
                    <span className="ml-1 text-[10px] text-gray-400" title="Strict mode: all text content was stripped from this step.">strict privacy</span>
                  )}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>

      {events.length === 0 && (
        <p className="mt-6 rounded-lg border border-gray-200 p-8 text-center text-[13px] text-gray-400">
          No steps found for this conversation. The link may be wrong, or old data may have
          expired under your plan&apos;s retention window.
        </p>
      )}
    </div>
  );
}
